#!/bin/bash

# Jonathan Nusantara (jan265), Eric Hall (ewh73), Eric Kahn (edk52)
# Lab 2, 10-10-2020

# Will run in background
python more_video_control_cb.py &
 # Run in foreground
sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -input file=video_fifo -vo sdl -framedrop bigbuckbunny320p.mp4
